unbind C-b
set-option -g prefix C-e

bind n split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# modern colors
set -g default-terminal "tmux-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Avoid escape delay
set -sg escape-time 0

set -g mouse on
set -g status-style dim

set -g window-status-current-style fg=colour81
set -g window-status-current-style bold
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F 
